services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=personal-site-v0
    ports:
      - 7777:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
