import Header from "../_components/header";

type Project = {
    id: number;
    title: string;
    awards: string[];
    description: string;
    image: string;
    stack: string[];
    link: string;
}

const projects: Project[] = [
    {
        id: 1,
        title: "<ART>: Auto-Render-Together",
        awards: [],
        description: "an artistic reality terminal for generating config-based frequency visuals that can be rendered and shared across the platform",
        image: "images/dev/auto-render-together.png",
        stack: ["Typescript", "Clerk Auth", "Supabase", "Vercel", "React", "Tailwind CSS", "Shadcn UI"],
        link: "https://auto-render-together.vercel.app/artbuilder"
    },
    {
        id: 2,
        title: "SoundMoji 🏆",
        awards: ["First Prize @Fractal Tech NYC's Generative UI/UX Hackathon, February 2025"],
        description: "web application that allows users to create custom sounds with input from an emoji keyboard processed and generated by AI",
        image: "images/dev/soundmoji.png",
        stack: ["TypeScript", "Next.js", "Tailwind CSS", "TRPC", "DrizzleORM", "Shadcn UI", "OpenAI", "Fal.ai"],
        link: "https://genux-hackathon.vercel.app/"
    },
    {
        id: 3,
        title: "twitter community-archive chatbot",
        awards: [],
        description: "recreates a twitter user from the community-archive and allows users to hold a conversation with them. the user only responds in tweets",
        image: "images/dev/chatbot.png",
        stack: ["TypeScript", "Next.js", "Vercel AI SDK", "community-archive", "Prisma"],
        link: "https://github.com/fractal-tech-nyc/eribarrett-twitter-archive-chatbot"
    },
    {
        id: 4,
        title: "Game of Set",
        awards: [],
        description: "a Family Game of Visual Perception, with online playability",
        image: "images/dev/gameofset.png",
        stack: ["TypeScript", "React Router", "Tailwind CSS", "Express", "Socket.io"],
        link: "https://github.com/fractal-tech-nyc/eribarrett-game-of-set",
    },
    {
        id: 5,
        title: "dream-journal.py",
        awards: [],
        description: "a dream journal app that prompts the user to record their dreams each morning via SMS",
        image: "images/dev/dreamjournal.png",
        stack: ["Python", "Google API", "Twilio API"],
        link: "https://github.com/erosika/dream_journal"
    }
]
export default function DevPage() {
    return (
        <div className="flex flex-col min-h-screen h-full bg-red-200 dark:bg-gray-900 dark:bg-opacity-90 text-gray-900 dark:text-white font-mono fixed top-0 left-0 right-0 overflow-hidden">
            <Header />
            <div className="flex-1 overflow-y-auto px-4 md:px-8 py-6 max-w-4xl mx-auto w-full">
                <h1 className="text-xl lowercase tracking-wide mb-6 border-b border-gray-700 pb-2 font-medium">projects</h1>

                <div className="space-y-8">
                    {projects.map((project) => (
                        <div key={project.id} className="flex flex-col space-y-3 border-b border-gray-700 pb-8">
                            <div className="flex items-center justify-between">
                                <h2 className="text-lg lowercase tracking-wide font-medium">
                                    <a
                                        href={project.link}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="hover:text-blue-800 dark:hover:text-blue-300"
                                    >
                                        {project.title}
                                    </a>
                                </h2>
                                <a
                                    href={project.link}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-xs text-blue-600 dark:text-blue-300 hover:text-blue-800 dark:hover:text-blue-200"
                                >
                                    view →
                                </a>
                            </div>

                            {project.awards.length > 0 && (
                                <div className="text-xs text-amber-700 dark:text-yellow-300 font-medium">
                                    {project.awards.map((award, index) => (
                                        <div key={index}>{award}</div>
                                    ))}
                                </div>
                            )}

                            <div className="flex flex-col sm:flex-row gap-4">
                                <div className="sm:w-1/3">
                                    <a
                                        href={project.link}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className="block"
                                    >
                                        <img
                                            src={project.image}
                                            alt={project.title}
                                            className="w-full h-auto object-cover opacity-90 border border-gray-700 hover:opacity-100 transition-opacity"
                                        />
                                    </a>
                                </div>
                                <div className="sm:w-2/3 space-y-3">
                                    <p className="text-sm text-gray-900 dark:text-gray-100 font-medium">{project.description}</p>
                                    <div className="flex flex-wrap gap-1.5">
                                        {project.stack.map((tech, index) => (
                                            <span key={index} className="text-xs bg-gray-800 bg-opacity-80 text-white px-2 py-0.5 rounded">
                                                {tech}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    )
}



